<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenForma.Examples.Client</RootNamespace>
    <OpenApiGenerationMode>Client</OpenApiGenerationMode>
  </PropertyGroup>
  <ItemGroup>
    <OpenApiReference Include="../pets.yaml" />
  </ItemGroup>
</Project>
